# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-14 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180714_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_name',
            field=models.CharField(db_column='u_name', max_length=32, primary_key=True, serialize=False),
        ),
    ]
